version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go-web-server
  go-web-server:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./front:/app/front
  front:
    build: ./front
    ports:
      - 3000:3000
